"""
app/pages/ai_report.py
"""

import os
import streamlit as st
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

_root = Path(__file__).resolve().parent.parent.parent
load_dotenv(_root / ".env", override=True)

from app.db.queries import get_latest_ai_report, get_ai_report_history, get_latest_score
from data.pipeline.db_connection import get_connection


def _check_groq_status() -> tuple[bool, str]:
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if not api_key or api_key == "your_groq_api_key_here":
        return False, "GROQ_API_KEY not set"
    try:
        from groq import Groq
        return True, f"Key: {api_key[:8]}...{api_key[-4:]}"
    except ImportError:
        return False, "groq package not installed — run: pip install groq"


def render() -> None:
    st.title("AI Diagnostic Report")
    st.markdown(
        '<p style="color:#64748b;font-size:14px;margin-top:-4px;">Generated by LLaMA 3.1 via Groq API</p>',
        unsafe_allow_html=True,
    )
    st.divider()

    conn = get_connection()
    groq_ready, groq_msg = _check_groq_status()

    if not groq_ready:
        st.error(
            f"**Groq AI is not configured** — {groq_msg}\n\n"
            f"1. Open `{_root / '.env'}`\n"
            "2. Add: `GROQ_API_KEY=gsk_xxxxxxxxxxxxxxxxxxxx`\n"
            "3. Get a free key at https://console.groq.com/keys\n"
            "4. Run: `python test_groq.py` to verify\n"
            "5. Then: `python run_pipeline.py --mode ai`\n\n"
            "_Report below is rule-based fallback — accurate, but not AI-written._"
        )
    else:
        st.success(f"Groq AI ready — {groq_msg}")

    col_btn, col_info = st.columns([1, 3])
    with col_btn:
        if st.button("Regenerate Report", type="primary", disabled=not groq_ready):
            with st.spinner("Calling Groq API..."):
                try:
                    import yaml
                    with open(_root / "config.yaml") as f:
                        config = yaml.safe_load(f)
                    from ml.ai_layer.diagnostic import DiagnosticReporter
                    reporter = DiagnosticReporter(config)
                    reporter.generate_and_store(conn)
                    if reporter._last_error:
                        st.error(f"AI failed: {reporter._last_error}")
                    else:
                        st.success("New AI report generated.")
                        st.rerun()
                except Exception as exc:
                    st.error(f"Error: {exc}")
    with col_info:
        if groq_ready:
            st.caption("Generates a fresh AI report using current health scores.")

    st.divider()

    report = get_latest_ai_report(conn)
    score  = get_latest_score(conn)

    if report is None:
        st.warning("No reports yet. Run `python run_pipeline.py --mode full` or click Regenerate.")
        conn.close()
        return

    with st.expander("Score context for this report", expanded=False):
        if score:
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Composite",  f"{score['composite_score']:.1f}")
            c2.metric("Finance",    f"{score['finance_score']:.1f}")
            c3.metric("HR",         f"{score['hr_score']:.1f}")
            c4.metric("Operations", f"{score['ops_score']:.1f}")

        band  = str(report.get("score_band", ""))
        model = str(report.get("model_used", "unknown"))
        is_fb = bool(report.get("is_fallback", 0))
        st.markdown(
            f"**Date:** {report.get('report_date')} &nbsp;|&nbsp; "
            f"**Status:** {band} &nbsp;|&nbsp; "
            f"**Words:** {report.get('word_count', 0)} &nbsp;|&nbsp; "
            f"**Model:** `{model}` &nbsp;|&nbsp; "
            f"**Type:** {'Rule-based fallback' if is_fb else 'AI-generated'}"
        )

    st.markdown("### Latest Diagnostic Report")

    if report.get("is_fallback"):
        st.info(
            "This is a **rule-based fallback** report (Groq AI was unavailable). "
            "Set your `GROQ_API_KEY` in `.env` and click Regenerate for an AI report."
        )

    st.markdown(str(report.get("report_text", "No report text available.")))
    st.divider()

    st.markdown("### Report History")
    history_df = get_ai_report_history(conn, limit=30)

    if not history_df.empty:
        history_df["type"] = history_df["is_fallback"].map({0: "AI", 1: "Fallback"})
        display_df = history_df[["report_date", "composite_score", "score_band", "word_count", "type"]]
        display_df.columns = ["Date", "Score", "Status", "Words", "Type"]
        st.dataframe(display_df, use_container_width=True, hide_index=True)
    else:
        st.info("No report history yet.")

    conn.close()
